CREATE TABLE IF NOT EXISTS personas (
    persona_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    genero VARCHAR(20) NOT NULL,
    edad INTEGER NOT NULL CHECK (edad BETWEEN 0 AND 120),
    identificacion VARCHAR(20) NOT NULL UNIQUE,
    direccion VARCHAR(200),
    telefono VARCHAR(20),
    CONSTRAINT chk_personas_genero
        CHECK (genero IN ('MASCULINO', 'FEMENINO', 'OTRO'))
);

CREATE TABLE IF NOT EXISTS clientes (
    cliente_id BIGINT PRIMARY KEY,
    contrasena VARCHAR(255) NOT NULL,
    estado BOOLEAN NOT NULL,
    CONSTRAINT fk_clientes_personas
        FOREIGN KEY (cliente_id) REFERENCES personas (persona_id)
);

CREATE TABLE IF NOT EXISTS cuentas (
    cuenta_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_cuenta VARCHAR(30) NOT NULL UNIQUE,
    tipo_cuenta VARCHAR(20) NOT NULL,
    saldo_inicial NUMERIC(16, 2) NOT NULL CHECK (saldo_inicial >= 0.00),
    estado BOOLEAN NOT NULL,
    cliente_id BIGINT NOT NULL,
    CONSTRAINT fk_cuentas_clientes
        FOREIGN KEY (cliente_id) REFERENCES clientes (cliente_id),
    CONSTRAINT chk_cuentas_tipo
        CHECK (tipo_cuenta IN ('AHORROS', 'CORRIENTE'))
);

CREATE TABLE IF NOT EXISTS movimientos (
    movimiento_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id BIGINT NOT NULL,
    fecha TIMESTAMP NOT NULL,
    tipo_movimiento VARCHAR(20) NOT NULL,
    valor NUMERIC(16, 2) NOT NULL,
    saldo NUMERIC(16, 2) NOT NULL,
    CONSTRAINT fk_movimientos_cuentas
        FOREIGN KEY (cuenta_id) REFERENCES cuentas (cuenta_id),
    CONSTRAINT chk_movimientos_tipo
        CHECK (tipo_movimiento IN ('CREDITO', 'DEBITO'))
);

CREATE INDEX IF NOT EXISTS idx_cuentas_cliente_id
    ON cuentas (cliente_id);

CREATE INDEX IF NOT EXISTS idx_movimientos_cuenta_id
    ON movimientos (cuenta_id);

CREATE INDEX IF NOT EXISTS idx_movimientos_cuenta_fecha
    ON movimientos (cuenta_id, fecha);
