spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cuentas}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cuentas}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cuentas}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
